### ISSUE TITLE
Stack exhaustion in Chrome for complex files 

### ISSUE THREAD

**Issue by koczkatamas** [kaitai-io/kaitai_struct_webide#14]
I don't know exact details, but probably parsing a complex file can use all the allowed stack up in Chrome.

(@xavrr mentioned the issue on Gitter: "is there a way to increase the stack size for chrome ? to allow for bigger size parsing ?")

**Comment by GreyCat** [comment]
I've played around a bit, minimal example like that:

```yaml
meta:
  id: example
seq:
  - id: foo
    type: u1
    repeat: eos
```

gets on any large enough file (like >1 MB)

```
Parse error (RangeError): Maximum call stack size exceeded
Call stack: RangeError: Maximum call stack size exceeded
    at SortedList.splice (<anonymous>)
    at SortedList.insert (https://ide.kaitai.io/lib/interval-tree2/interval-tree.js:88:18)
    at Node.insert (https://ide.kaitai.io/lib/interval-tree2/interval-tree.js:342:25)
    at IntervalTree.insert (https://ide.kaitai.io/lib/interval-tree2/interval-tree.js:714:14)
    at IntervalTree.insert (https://ide.kaitai.io/lib/interval-tree2/interval-tree.js:712:23)
    at IntervalTree.insert (https://ide.kaitai.io/lib/interval-tree2/interval-tree.js:712:23)
    at IntervalTree.insert (https://ide.kaitai.io/lib/interval-tree2/interval-tree.js:712:23)
    at IntervalTree.insert (https://ide.kaitai.io/lib/interval-tree2/interval-tree.js:712:23)
    at IntervalTree.insert (https://ide.kaitai.io/lib/interval-tree2/interval-tree.js:712:23)
    at IntervalTree.insert (https://ide.kaitai.io/lib/interval-tree2/interval-tree.js:712:23) RangeError: Maximum call stack size exceeded
```

**Comment by koczkatamas** [comment]
@xavrr: could you try it out again with the current devel WebIDE ( https://ide.kaitai.io/devel/ )?

This ksy works with sample1.iso:

```yaml
meta:
  id: crash1
  file-extension: crash1
seq:
  - id: foo
    type: u4le
    repeat: eos
```

**Comment by GreyCat** [comment]
Confirming, it works now.

I noticed that initial parsing is pretty slow, takes ~15 seconds on my box and whole Chromium tab is irresponsible while it is doing the parse — though after that, it works perfectly.

I guess, ideally it should run somehow in a parallel worker, and there should be some progress bar or at least some progress indication (like "Parsing now, please wait..." somewhere) and a timer going on. Also, a "cancel parsing" button would be nice ;)

But that's just my imagination running wild ;)

**Comment by koczkatamas** [comment]
Yeah, I consider that a different task (it's already there as a wishlist item: "Smooth experience with big files too (progress bar / cancelable operations)").

Actually the parsing is running parallel and does not block the UI. It can be a bit surprising but those seconds are elapsed with copying the results from the worker to the UI "world".

I was thinking about some architectural changes to solve this issue. But I considered it low priority. Btw sample1.iso + this ksy took ~3 sec on my machine.

**Comment by koczkatamas** [comment]
I published the changes to stable. If you find any problem with this change, please reopen the issue.
